INSERT INTO "MfFactor" ("type", "id", "embedding", "error")
SELECT 'USER', "id", l2_normalize(ARRAY[
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random()
]::halfvec(384)), 0.0
FROM "User";
