INSERT INTO "MfFactor" ("type", "id", "embedding", "error")
SELECT 'MEDIA', "id", l2_normalize(ARRAY[
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random(), random(), random(), random(), random(), random(), random(),
	random(), random(), random(), random()
]::halfvec(384)), 0.0
FROM "Media"
WHERE "popularity" > 10;
